### ISSUE TITLE
Need some guidance to help

### ISSUE THREAD

**Issue by songoku119** [jhewt/gumer-psn#16]
I started sniffing the traffic from the app so I can help out.  The duid that I have is different than the one you have.  Did you find that this is different across devices too?  I'm still looking for the client_secret to see if it's any different from what you posted as well.

- EDIT: Client id is still the same as well as the client secret.  So far duid looks different only.

**Comment by xXREDXIIIIXx** [comment]
I did the whole sniffing the app thing but considering i didn't make the original I have no idea what has actually changed.

**Comment by songoku119** [comment]
I'm on the same boat, so I was just going line by line in the files from the repo.  It's definitely a change in the way that the request is made though (maybe a missing parm) as it fails right off the bat as the req object seems to be invalid

**Comment by jhewt** [comment]
This has been fixed, they only changed a few params and a new redirect. Now, there's a new field in the login post called "params" with the same content as the header before but now as Base64.
