### ISSUE TITLE
socket hangup

### ISSUE THREAD

**Issue by freeseus** [jhewt/gumer-psn#18]
I'm getting a socket hangup in the example.

**Comment by freeseus** [comment]
Maybe it's getting this if an IP address hits it too frequently? Closing and restarting the node server still gets the error. It *appears* if you wait a while (at least an hour?) it'll start working again.

**Comment by freeseus** [comment]
When it doesn't get a socket hangup, I get this:
![errorinexample](https://cloud.githubusercontent.com/assets/11297204/9695599/6489728e-5331-11e5-9de5-9c60caa874a2.png)

**Comment by jhewt** [comment]
Regex is failing because there is no redirection. Have you tried to log in with the same account directly on PSN's site?
Comment those lines and only log the entire response
```js
console.log('response', response);
// Or maybe just the header to see what response code is returning
console.log('response', response.headers);
```

**Comment by freeseus** [comment]
response headers:

![responseheaders](https://cloud.githubusercontent.com/assets/11297204/9696672/adc50132-5342-11e5-9f11-2f4dfafb441c.png)

**Comment by jhewt** [comment]
Try with 
```js
console.log('response', response);
```

**Comment by freeseus** [comment]
console.log('response', response);

![part1](https://cloud.githubusercontent.com/assets/11297204/9696766/f28c8126-5344-11e5-8eac-a9207fb5af67.png)
![part2](https://cloud.githubusercontent.com/assets/11297204/9696769/f5ecedd8-5344-11e5-80cb-33341210007a.png)
![part3](https://cloud.githubusercontent.com/assets/11297204/9696770/fa2ae9cc-5344-11e5-8597-df6af7405da8.png)

**Comment by jhewt** [comment]
I confirm is a bug in gumer-psn, apparently some subtle change has been introduced.
I'll get my hands on it as soon my Nexus 5 comes back to life, it is dead becaouse of me trying to install Android M (6.0) with a faulty cable lol

**Comment by jhewt** [comment]
Have you changed the login details? You should change {{CHANGE_ME}}.

**Comment by jhewt** [comment]
It wasn't working for me because I was behind a firewall, without it is working perfectly.

**Comment by freeseus** [comment]
I don't think I'm behind a firewall - I am on DSL at the location I'm currently testing at.

![login](https://cloud.githubusercontent.com/assets/11297204/9697827/b623d8a2-536b-11e5-9f9d-7cad64eeb122.png)

**Comment by jhewt** [comment]
Remove the brackets, those aren't supposed to go there.
I added them just to call attention because many devs creating issues about login not working with invalid credentials, it's not a template tag :P

**Comment by freeseus** [comment]
That worked - thank you!
