### ISSUE TITLE
freezes under high concurrency

### ISSUE THREAD

**Issue by techpulse** [jhewt/gumer-psn#31]
i wrote a script to test the concurrency, on grabbing psn profiles - since there is no limit doing so on Sony's end.

However, the script just froze when we reached to maybe like 1500? 

any reason to this? my server is a beast and should be able to handle it, would be script's fault.

**Comment by techpulse** [comment]
nvm, must be

{"error":true,"message":"Something went terribly wrong, submit an issue on GitHub please!","response":{"error":{"code":2105867,"message":"Rate limit exceeded"}}}

causing it lol, thought there was none.. must be higher than 150 thats for sure, i sent 1500 before it happen.

**Comment by jhewt** [comment]
You sent 1500 request but that doesn't mean that all requests were processed and returned data. I'm pretty sure it actually processed around 200 and then timeout'd the rest or returned the error json.
Also node.js is single threaded, even the biggest of monster servers will average on the same number unless you use node's cluster implentation, and there's a few other soft and hard limits such as open files for the request connection, open connections, etc
