### ISSUE TITLE
error login

### ISSUE THREAD

**Issue by firstsko** [jhewt/gumer-psn#8]
[root@10-4-5-5 gumer-psn]# node app.js 
gPSN | Getting login
gPSN | Asking for new token
gPSN | Login for the first time
gPSN | ERROR: {"error":"4098","error_description":"Mandatory parameter 'code' is missing","docs":"http://docs.auth.api.ac.playstation.net/oauth/token","error_code":4098}
gPSN | authCode obtained: k97y2D
gPSN | Login for the first time
gPSN | access_token/refresh_token obtained: {"access_token":"a1f1678e-c7e2-4890-b506-897bb36d61fd","token_type":"bearer","refresh_token":"ba2fa306-9b07-4baf-b5b0-0b128659ffe5","expires_in":3599,"scope":"psn:sceapp"}

**Comment by ivolazy** [comment]
Starting gPSN
gPSN | Getting login
express deprecated router.param(fn): Refactor to use path params ../../node_modules/express/lib/application.js:331:16
gumerPSN Example running at http://localhost:3000/
gPSN | ERROR: Error: options.uri is a required argument
gPSN | Asking for new token
gPSN | Login for the first time
gPSN | ERROR: {"code":"ECONNRESET"}

**Comment by ivolazy** [comment]
I'm getting a mix of the same "Mandatory parameter 'code' is missing" and the ECONNRESET errors
